version: '3.7'

services:
  sneedznab:
    image: ghcr.io/turbocheetah/sneedznab:latest
    container_name: sneedznab
    environment:
      - NYAA_ENABLED=true
      # AnimeTosho is only useful if you want NZBs
      - ANIMETOSHO_ENABLED=false
      - RUTRACKER_ENABLED=true
      # Only enable AB if you have access to it
      - ANIMEBYTES_ENABLED=false
      - ANIMEBYTES_PASSKEY=
      - ANIMEBYTES_USERNAME=
      # If using Redis cache set the URL and token using the values from Upstash
      - REDIS_ENABLED=false
      - REDIS_URL=
      - REDIS_TOKEN=
      - CACHE_TTL=120
      - DEBUG=true
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
