version: '3.7'

services:
  sneedznab:
    image: ghcr.io/turbocheetah/sneedznab:v1.1
    container_name: sneedznab
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
