name: Lint Title

on:
  pull_request:
    branches: ["*"]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    name: Validate PR Title
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
